export const datas = [
  {
    field: "2022",
    barChartDatas: {
      labels: [
        "Jan-22",
        "Feb-22",
        "Mar-22",
        "Apr-22",
        "May-22",
        "Jun-22",
        "July-22",
        "Aug-22",
        "Sep-22",
        "Oct-22",
        "Nov-22",
        "Dec-22",
      ],
      datasets: [
        {
          label: "Data 22",
          backgroundColor: "#7a7878",
          data: [20, 10, 62, 70, 25, 49, 35, 54, 34, 77, 32, 10],
        },
      ],
    },
    donutChartDatas: {
      labels: [
        "AWALI CRUDE OIL",
        "ABU SA'AFA FIELD",
        "GAS SALES",
        "BLING",
        "SUBSIDES",
        "DIVIDENDS",
        "OTHER",
      ],
      datasets: [
        {
          label: "Data One",
          backgroundColor: [
            "#5ecbdf",
            "#2a618b",
            "#41B883",
            "#edce72",
            "#df737e",
            "#7a7878",
            "#dfa573",
          ],
          data: [60, 10, 12, 0, 15, 25, 43],
        },
      ],
    },
    varianceTable: [
      {
        id: 1,
        name: "AWALI CRUDE OIL",
        budget: "600m",
        yearToDate: "600m",
        yearEnd: "600m",
        variance: "600m",
        status: "Not Started",
        percentage: 2.5,
      },
      {
        id: 2,
        name: "ABU SA'AFA FIELD",
        budget: "500m",
        yearToDate: "500m",
        yearEnd: "500m",
        variance: "500m",
        status: "Behind Schedule",
        percentage: 2.5,
      },
      {
        id: 3,
        name: "GAS SALES",
        budget: "500m",
        yearToDate: "500m",
        yearEnd: "500m",
        variance: "500m",
        status: "On Target",
        percentage: 2.5,
      },
      {
        id: 4,
        name: "BLING",
        budget: "500m",
        yearToDate: "500m",
        yearEnd: "500m",
        variance: "500m",
        status: "Not Started",
        percentage: 2.5,
      },
      {
        id: 5,
        name: "SUBSIDES",
        budget: "500m",
        yearToDate: "500m",
        yearEnd: "500m",
        variance: "500m",
        status: "Not Started",
        percentage: 2.5,
      },
      {
        id: 6,
        name: "DIVIDENDS",
        budget: "500m",
        yearToDate: "500m",
        yearEnd: "500m",
        variance: "500m",
        status: "Not Started",
        percentage: 2.5,
      },
      {
        id: 7,
        name: "OTHER",
        budget: "500m",
        yearToDate: "500m",
        yearEnd: "500m",
        variance: "500m",
        status: "On Target",
        percentage: 2.5,
      },
      {
        id: 8,
        name: "TOTAL",
        budget: "500m",
        yearToDate: "500m",
        yearEnd: "500m",
        variance: "500m",
        status: "Not Started",
        percentage: 2.5,
      },
    ],
  },
  {
    field: "2021",
    barChartDatas: {
      labels: [
        "Jan-21",
        "Feb-21",
        "Mar-21",
        "Apr-21",
        "May-21",
        "Jun-21",
        "July-21",
        "Aug-21",
        "Sep-21",
        "Oct-21",
        "Nov-21",
        "Dec-21",
      ],
      datasets: [
        {
          label: "Data One",
          backgroundColor: "#7a7878",
          data: [40, 30, 42, 50, 45, 39, 35, 38, 40, 46, 50, 30],
        },
      ],
    },
    donutChartDatas: {
      labels: [
        "AWALI CRUDE OIL",
        "ABU SA'AFA FIELD",
        "GAS SALES",
        "BLING",
        "SUBSIDES",
        "DIVIDENDS",
        "OTHER",
      ],
      datasets: [
        {
          label: "Data One",
          backgroundColor: [
            "#5ecbdf",
            "#2a618b",
            "#41B883",
            "#edce72",
            "#df737e",
            "#7a7878",
            "#dfa573",
          ],
          data: [40, 20, 12, 20, 45, 39, 29],
        },
      ],
    },
    varianceTable: [
      {
        id: 1,
        name: "AWALI CRUDE OIL",
        budget: "1,600m",
        yearToDate: "1,600m",
        yearEnd: "1,600m",
        variance: "1,600m",
        status: "Not Started",
        percentage: 2.5,
      },
      {
        id: 2,
        name: "ABU SA'AFA FIELD",
        budget: "100m",
        yearToDate: "100m",
        yearEnd: "100m",
        variance: "100m",
        status: "Behind Schedule",
        percentage: 2.5,
      },
      {
        id: 3,
        name: "GAS SALES",
        budget: "100m",
        yearToDate: "100m",
        yearEnd: "100m",
        variance: "100m",
        status: "On Target",
        percentage: 2.5,
      },
      {
        id: 4,
        name: "BLING",
        budget: "100m",
        yearToDate: "100m",
        yearEnd: "100m",
        variance: "100m",
        status: "Not Started",
        percentage: 2.5,
      },
      {
        id: 5,
        name: "SUBSIDES",
        budget: "100m",
        yearToDate: "100m",
        yearEnd: "100m",
        variance: "100m",
        status: "Not Started",
        percentage: 2.5,
      },
      {
        id: 6,
        name: "DIVIDENDS",
        budget: "100m",
        yearToDate: "100m",
        yearEnd: "100m",
        variance: "100m",
        status: "Not Started",
        percentage: 2.5,
      },
      {
        id: 7,
        name: "OTHER",
        budget: "100m",
        yearToDate: "100m",
        yearEnd: "100m",
        variance: "100m",
        status: "On Target",
        percentage: 2.5,
      },
      {
        id: 8,
        name: "TOTAL",
        budget: "100m",
        yearToDate: "100m",
        yearEnd: "100m",
        variance: "100m",
        status: "Not Started",
        percentage: 2.5,
      },
    ],
  },
];
